version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_for_vkr
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nadeaklass0909/vkr_frontend:latest
    ports:
      - "8082:80"
    depends_on:
      - backend

  backend:
    image: nadeaklass0909/vkr_backend:latest
    ports:
      - "8002:8000"


volumes:
  pg_data:
