version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_for_vkr
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    #image: nadeaklass0909/vkr_frontend:latest
    build:
      context: frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

  backend:
    build:
      context: backend
    working_dir: /app/backend
    environment:
      - PYTHONPATH=/app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - "8002:8000"
    volumes:
      - .:/app


volumes:
  pg_data:
