version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  client:
    image: fastui
    ports:
      - "8000:8000"


volumes:
  pg_data:
